#' Title
#'
#' @param data 
#' @param data_ 
#' @param data_attributes 
#' @param output.name 
#' @param output.type 
#' @param overwrite 
#' @param last.entry 
#'
#' @return
#' @export
#'
#'
.pack_data <- function(data, 
                       data_, 
                       data_attributes, 
                       output.name, 
                       output.type, 
                       overwrite = F, 
                       last.entry = output.name) {
  
  # Direct output of data
  if (hasArg(output.type) && 
      !grepl(pattern = "list_", x = output.type)) {
    return(data)
  } else if (!hasArg(output.type) && (!hasArg(data_) || !"list_" %in% class(data_))) {
    return(data)
  }
  
  
  # If list_ output
  
  # Control if data_ input given
  if (hasArg(data_)) {
    
    # Is data_ a list_ object
    if (!"list_" %in% class(data_)) {
      stop("The <data_> argument must be a list generated by the list_() function.", call. = FALSE)
     
    # No output name 
    } else if (!hasArg(output.name)) {
      stop("No <output.name> defined.", call. = FALSE)
      
      # Output name already in data
    } else if (output.name %in% names(data_) && !overwrite) {
      stop("<output.name> must not already exist in data_. Set a unique name.", 
           call. = FALSE)
    }
    
  # No data_ given
  } else {
    data_ <- list_()
  }
  
  # Set attributes and store data in data_ list
  data_[[output.name]] <- .set_data_attributes(data, data_attributes)
  
  attr(data_, "last_entry") <- last.entry
  
  return(data_)
  
}


#' Title
#'
#' @param data_ 
#' @param input.name 
#'
#' @return
#' @export
#'
#'
.unpack_data <- function(data_, input.name) {
  
  # Check input
  if (!hasArg(data_)) stop("No <data_> given.", call. = FALSE)
  
  # Test for list_ input
  if ("list_" %in% class(data_)) {
    # input.name argument
    if (!hasArg(input.name)) input.name <- attr(data_, "last_entry")
    
    if (is.null(data_[[input.name]]))
      stop(paste0("Could not find <input.name> ", input.name, " in <data_> list."), 
           call. = FALSE)
    
    data <- data_[[input.name]]
    attr(data, "input.name") <- input.name
    
    # Regular data input
  } else {
    data <- data_
  }
  
  return(data)
}


#' Title
#'
#' @param data_ 
#' @param input.names 
#'
#' @return
#' @export
#'
#' 
.unpack_data_m <- function(data_, input.names) {
  
  # Check input
  if (!hasArg(data_)) stop("No <data_> given.", call. = FALSE)
  
  # Test for list_ input
  if ("list_" %in% class(data_)) {
    # input.name argument
    if (!hasArg(input.names)) stop("Define all <input.names>.")
    if (any(is.null(data_[input.names]))) 
      stop(paste0("Could not find <input.names> ", 
                  paste(setdiff(input.names, names(data_)), collapse = ", "), 
                  " in <data_> list."), 
           call. = FALSE)
    else {
      data <- data_[input.names]
      attr(data, "input.name") <- input.names
    }
    
    # Regular data input
  } else {
    data <- data_
  }
  
  return(data)
}


#' Saves relevant data attributes in list
#'
#' @param data data object with
#'
#' @return
#' @export
#'
#'
.get_data_attributes <- function(data) {
  
  data_attributes <- attributes(data)
  
  data_attributes <- data_attributes[names(data_attributes) %in% 
                                       c("dataset",
                                         "variables",
                                         "observations", 
                                         "data_info")]
  
  if (length(data_attributes) == 0) data_attributes <- NULL
  
  # Return
  return(data_attributes)
  
}


#' Sets relevant data attributes from list
#'
#' @param data data object with specific attributes
#' @param data_attributes list of data_attributes
#'
#' @return
#' @export
#'
#'
.set_data_attributes <- function(data, data_attributes) {
  
  if (is.null(data_attributes) || !tibble::is_tibble(data)) 
    return(data)
  
  # Update attributes
  # variables column
  if (names(data)[1] == "variables") {
    data_attributes[["variables"]] <- intersect(data_attributes[["variables"]], 
                                                data$variables)
    data_attributes[["observations"]] <- intersect(data_attributes[["observations"]], 
                                                   names(data))
    # observations column
  } else if (names(data)[1] == "observations") {
    data_attributes[["observations"]] <- intersect(data_attributes[["observations"]], 
                                                   data$observations)
    data_attributes[["variables"]] <- intersect(data_attributes[["variables"]], 
                                                names(data))
  }
  
  # data info columns
  data_attributes[["data_info"]] <- intersect(data_attributes[["data_info"]], 
                                              names(data))
  
  
  for (i in intersect(names(data_attributes), c("dataset", 
                                                "variables", 
                                                "observations", 
                                                "data_info"))) {
    attr(data, i) <- data_attributes[[i]]
  }
  
  # Return
  return(data)
  
}


#' Sets relevant data attributes from list
#'
#' @param data_attributes_list list of data_attribute lists
#'
#' @return
#' @export
#'
#'
.merge_data_attributes <- function(data_attributes_list) {
  
  data_attributes <- data_attributes_list[[1]]
  
  for (i in 2:length(data_attributes_list)) {
    # dataset
    data_attributes[["dataset"]] <- unique(data_attributes[["dataset"]], 
                                           data_attributes_list[[i]][["dataset"]])
    # variables
    data_attributes[["variables"]] <- unique(data_attributes[["variables"]], 
                                             data_attributes_list[[i]][["variables"]])
    # observations
    data_attributes[["observations"]] <- unique(data_attributes[["observations"]], 
                                                data_attributes_list[[i]][["observations"]])
    
    # data_info
    data_attributes[["data_info"]] <- unique(data_attributes[["data_info"]], 
                                                    data_attributes_list[[i]][["data_info"]])
  }
  
  return(data_attributes)
  
}


#' Get column names containing data independently if variables or data columns
#'
#' @param data_attributes data_attributes list
#'
#' @return
#' @export
#'
#'
.data_columns <- function(data, data_attributes) {
  
  # columns entry determines which attribute to use for column names
  data_cols <- setdiff(names(data), 
                       c("variables", 
                         "observations", 
                         data_attributes[["data_info"]]))
  
  # Return
  return(data_cols)
  
}


